### ISSUE TITLE
Works perfect on 8.1

### ISSUE THREAD

**Issue by typoman76** [Mesuva/msv_add_multiple_pages#2]
Dear Ryan
Thank you for this package. Helped me to get the sitemap quickly filled up. 
I used this with 8.1 and it worked perfectly. You can change your description text :-)

best regards, Roland

**Comment by Mesuva** [comment]
Thanks Roland, glad to hear it was useful to you. We don't use it ourselves very often, but when we _do_ need it we find it's essential!

Cheers!
